server {
    listen 80;
    server_name app.captaincargo.co 64.227.153.54 _;

    root /var/www/frontend;
    index index.html;

    location = /ngsw.json {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location = /ngsw-worker.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://127.0.0.1:5000;
    }
}

